package ExceptionsAndErrorHandling;

import java.util.Arrays;
import java.util.Scanner;

public class NumberInRange_lab1 {
    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);

        int[] range = Arrays.stream(scanner.nextLine().split("\\s+")).mapToInt(Integer::parseInt).toArray();
        int minRange = range[0];
        int maxRange = range[1];
        System.out.printf("Range: [%d...%d]%n", minRange, maxRange);

        numberIsInRange(scanner, range);
    }

    private static void numberIsInRange(Scanner scanner, int[] range) {
        String input = scanner.nextLine();
        try {
            int number = Integer.parseInt(input);
            if (number >= range[0] && number <= range[1]) {
                System.out.printf("Valid number: %d%n", number);
                return;
            } else {
                System.out.printf("Invalid number: %d%n", number);
            }
        } catch (Exception exception) {
            System.out.printf("Invalid number: %s%n", input);
        }
       numberIsInRange(scanner, range);
    }
}

